name = "mirror"
compatibility_date = "2026-04-30"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1df1ad05141d49c39273dc264e83135e"
preview_id = "cac31ca855d3447d8281a786cf4ebd9b"
